version: "3"

services:
  traefik:
    image: traefik:v3.3.2
    command:
      - "--global.sendAnonymousUsage"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.swarm.network=global_router"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http3"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.websecure.http.tls.certresolver=le"
      - "--entrypoints.websecure.http3"
      - "--certificatesResolvers.le.acme.email=${CERTIFICATESRESOLVERS_LE_ACME_EMAIL:?please export CERTIFICATESRESOLVERS_LE_ACME_EMAIL}"
      - "--certificatesResolvers.le.acme.storage=/external/data/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    ports:
      - 80:80
      - 443:443
    networks:
      - global_router
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=${TRAEFIK_HTTP_ROUTERS_HOST_RULE:?please export TRAEFIK_HTTP_ROUTERS_HOST_RULE}"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.middlewares=api-auth"
        - "traefik.http.middlewares.api-auth.basicauth.users=${TRAEFIK_HTTP_MIDDLEWARES_API_AUTH_BASICAUTH_USERS:?please export TRAEFIK_HTTP_MIDDLEWARES_API_AUTH_BASICAUTH_USERS}"
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/data/traefik2:/external/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

networks:
  global_router:
    external: true
